
const SELECT_PRODUCT = 'SELECT_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const SET_PRODUCTS = 'SET_PRODUCTS';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const ADD_PRODUCT = 'ADD_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export default {
    SELECT_PRODUCT,
    DELETE_PRODUCT,
    ADD_PRODUCT,
    FETCH_PRODUCTS,
    UPDATE_PRODUCT
}